---
title: "MBViz demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MBViz demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(magrittr)
library(MBViz)
library(ade4)
library(adegraphics)
library(ggplot2)
theme_set(theme_light())
```


## On simulated data

```{r}

n <- 200 # number of observations
p <- 3:5 # number of variables in each X block
q <- 5 # number of variables in Y
Xs <- matrix(rnorm(n * sum(p)), nrow = n, ncol = sum(p)) %>% as_blocks(., p = p)
Y <- matrix(rnorm(n * q), nrow = n, ncol = q) %>% list(Y = .)

plot_mtb_blocks(Xs = Xs, Y = Y)
plot_mtb_data(Xs = Xs, Y = Y)

```


```{r}

PLS_A <- mbpls(
  dudiY = dudi.pca(df = Y$Y, scannf = FALSE, nf = 2),
  ktabX = ktab.list.df(list(X = Xs %>% blocks_to_df())),
  scale = TRUE,
  scannf = FALSE, nf = 2
)

plot_mtb(PLS_A)

```








## On the `chicken` data from the `ade4` package

```{r}

data("chickenk")

```

```{r}
Y <- chickenk[1] # Mortality
Xs <- chickenk[2:5]
plot_mtb_blocks(Xs = Xs , Y = Y)
```

```{r}
plot_mtb_data(Xs = Xs, Y = Y)
```

```{r}

res <- 
  mbpls(
    dudiY = dudi.pca(Y$Mortality, scannf = FALSE, nf = 2),
    ktabX = ktab.list.df(Xs),
    scale = TRUE,
    scannf = FALSE, nf = 4
    )

```


We can plot the results with the `adegraphics` `plot` function:

```{r}

plot(res)

```

Or use the `MBViz` functions that allow customization.

```{r}

plot_mtb_eig(res, xaxis = 1, yaxis = 2)

```

```{r}

plot_mtb_lX(res) 
# plot_mtb_lX(res, samples_color = Y$Mortality/rowSums(Y$Mortality)
# plot_mtb_lX(res, samples_color = sample(c(1,2), size = res$lw %>% sum(), replace = TRUE))

```

```{r}

plot_mtb_lY(res)
# plot_mtb_Y(res, samples_color = Y$Mortality/rowSums(Y$Mortality))
# BUGGY plot_mtb_Y(res, samples_color = sample(c(1,2), size = res$lw %>% sum(), replace = TRUE))

```

```{r}

plot_mtb_cov(res)

```


```{r}

plot_mtb_Xloadings(res)

```

```{r}

plot_mtb(res)

```


```{r}

plot_varX_varY(res = res, varX = "NbChick", varY = "Condemn")

```





```{r}


set.seed(123456)
test_res <- testdim(res, nrepet = 199, optdim = 4)
boot <- randboot(res, nrepet = 100, optdim = res$nf)


```

```{r}

plot_mtb_vipc(res = res, boot = boot)
plot_mtb_bipc(res = res, boot = boot)
plot_mtb_coef(res = res, boot = boot, Y_var = 1)

```


